// Playwright exporter — turns a recorded journey into a runnable spec file.
//
// A journey recorded in Braiwser is already a precise, selector-anchored step
// list with assertions; this renders it as idiomatic @playwright/test code so
// the review artefact becomes a real regression test in the user's repo.
// Pure function, no I/O.

const NAV = 'navigate';

function quote(value) {
  return JSON.stringify(String(value == null ? '' : value));
}

// Playwright's `page.getByX` is nicer, but recorded steps are CSS selectors, so
// page.locator() is the faithful mapping. Selectors are emitted verbatim.
function loc(selector) {
  return `page.locator(${quote(selector)})`;
}

function testName(recording) {
  return (recording && recording.name) || 'recorded journey';
}

function specFileName(recording) {
  const slug = String(testName(recording))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return `${slug || 'journey'}.spec.js`;
}

function assertLine(step) {
  const kind = step.kind || 'exists';
  const op = step.op || 'contains';
  const expected = step.expected;

  if (kind === 'url') {
    if (op === 'equals') return `  await expect(page).toHaveURL(${quote(expected)});`;
    if (op === 'matches') return `  await expect(page).toHaveURL(new RegExp(${quote(expected)}));`;
    return `  await expect(page).toHaveURL(new RegExp(${quote(escapeRegex(expected))}));`;
  }
  if (!step.selector) return `  // (skipped ${kind} assertion — no selector recorded)`;

  switch (kind) {
    case 'exists':
      return `  await expect(${loc(step.selector)}).toHaveCount(1, { timeout: 5000 });`;
    case 'visible':
      return `  await expect(${loc(step.selector)}.first()).toBeVisible();`;
    case 'count': {
      const n = Number(expected);
      const count = Number.isFinite(n) ? n : 0;
      if (op === 'contains') {
        // "contains" means "at least" for counts (see config.ASSERTION_KINDS).
        return `  expect(await ${loc(step.selector)}.count()).toBeGreaterThanOrEqual(${count});`;
      }
      return `  await expect(${loc(step.selector)}).toHaveCount(${count});`;
    }
    case 'text':
    default:
      if (op === 'equals') return `  await expect(${loc(step.selector)}.first()).toHaveText(${quote(expected)});`;
      if (op === 'matches') return `  await expect(${loc(step.selector)}.first()).toHaveText(new RegExp(${quote(expected)}));`;
      return `  await expect(${loc(step.selector)}.first()).toContainText(${quote(expected)});`;
  }
}

function escapeRegex(s) {
  return String(s == null ? '' : s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function stepLines(step) {
  switch (step.type) {
    case NAV:
      return [`  await page.goto(${quote(step.url)});`];
    case 'click':
      return [`  await ${loc(step.selector)}.first().click();`];
    case 'input': {
      if (typeof step.value === 'boolean') {
        return [`  await ${loc(step.selector)}.first().setChecked(${step.value});`];
      }
      return [`  await ${loc(step.selector)}.first().fill(${quote(step.value)});`];
    }
    case 'key':
      return [`  await ${loc(step.selector)}.first().press(${quote(step.key || 'Enter')});`];
    case 'scroll':
      return [`  await page.evaluate(() => window.scrollTo(${Number(step.x) || 0}, ${Number(step.y) || 0}));`];
    case 'assert':
      return [assertLine(step)];
    default:
      return [`  // unsupported step: ${step.type}`];
  }
}

// recording: { name, startUrl, steps[] }
// returns { defaultName, content }
function toPlaywrightSpec(recording) {
  const rec = recording || {};
  const steps = Array.isArray(rec.steps) ? rec.steps : [];
  const out = [];

  out.push('// Generated by Braiwser from the recorded journey ' + quote(testName(rec)) + '.');
  out.push('// Run with:  npx playwright test');
  out.push("import { test, expect } from '@playwright/test';");
  out.push('');
  out.push(`test(${quote(testName(rec))}, async ({ page }) => {`);

  if (!steps.length) {
    out.push('  // This journey has no steps yet.');
  } else {
    // A journey always starts somewhere; if the first step is not a navigate,
    // fall back to the recorded startUrl so the spec is self-contained.
    if (steps[0].type !== NAV && rec.startUrl) {
      out.push(`  await page.goto(${quote(rec.startUrl)});`);
    }
    for (const step of steps) out.push(...stepLines(step));
  }

  out.push('});');
  out.push('');
  return { defaultName: specFileName(rec), content: out.join('\n') };
}

// Raw journey JSON, for archiving or re-import.
function toRecordingJson(recording) {
  const rec = recording || {};
  return {
    defaultName: (specFileName(rec).replace(/\.spec\.js$/, '') || 'journey') + '.json',
    content: JSON.stringify({ recording: rec, exportedAt: new Date().toISOString() }, null, 2),
  };
}

module.exports = { toPlaywrightSpec, toRecordingJson, specFileName };
