// Reviewer checklists and agency client-pack / static HTML report builders.
const { REVIEW_CHECKLISTS } = require('../../config');
const { toMarkdown } = require('../export/markdown');

function listChecklists() {
  return REVIEW_CHECKLISTS.slice();
}

function checklistSessionNotes(checklistId) {
  const cl = REVIEW_CHECKLISTS.find((c) => c.id === checklistId);
  if (!cl) return [];
  return cl.items.map((item, i) => ({
    kind: 'element',
    action: 'comment',
    note: `[Checklist: ${cl.label}] ${item}`,
    priority: 'normal',
    status: 'open',
    sortOrder: i,
    target: { selector: 'body', text: item },
  }));
}

function buildClientPack({ session, annotations, project, settings, recordingMeta }) {
  const agency = (settings && settings.agency) || {};
  const clientNotes = (annotations || []).filter((a) => a.visibility === 'client' || a.visibility !== 'internal');
  const notes = clientNotes.length ? clientNotes : annotations;
  const md = toMarkdown(session || {}, notes || [], null);
  const title = `${agency.name ? agency.name + ' — ' : ''}${session && session.name ? session.name : 'Review'}`;
  return {
    title,
    markdown: [
      `# ${title}`,
      '',
      agency.name ? `Prepared by **${agency.name}**` : '',
      session && session.url ? `URL: ${session.url}` : '',
      recordingMeta ? `Journey: ${recordingMeta.name || 'Recording'}` : '',
      '',
      md,
    ].filter(Boolean).join('\n'),
    noteCount: (notes || []).length,
    agencyName: agency.name || '',
    hasLogo: !!(agency.logoDataUrl),
  };
}

function buildHtmlReport({ session, annotations, project, settings }) {
  const pack = buildClientPack({ session, annotations, project, settings });
  const rows = (annotations || []).map((a, i) => {
    const sel = (a.target && (a.target.selector || a.target.id)) || '';
    return `<tr>
      <td>${i + 1}</td>
      <td>${escapeHtml(a.action || '')}</td>
      <td>${escapeHtml(a.priority || '')}</td>
      <td>${escapeHtml(a.visibility || 'internal')}</td>
      <td>${escapeHtml(a.note || '')}</td>
      <td><code>${escapeHtml(sel)}</code></td>
      <td>${a.viewport && a.viewport.w ? `${a.viewport.w}×${a.viewport.h}` : ''}</td>
    </tr>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${escapeHtml(pack.title)}</title>
<style>
  :root { color-scheme: light; --ink:#14201a; --muted:#5c6b63; --line:#d7e0d9; --bg:#f4f7f4; --accent:#1f6f4a; }
  body { margin:0; font: 15px/1.5 "Segoe UI", system-ui, sans-serif; color:var(--ink); background:var(--bg); }
  header { padding:48px 7vw 28px; background:linear-gradient(160deg,#1f6f4a 0%,#0e3d2a 100%); color:#f4f7f4; }
  h1 { margin:0 0 8px; font-size:clamp(28px,4vw,44px); letter-spacing:-0.03em; }
  .sub { opacity:.85; }
  main { padding:28px 7vw 64px; }
  table { width:100%; border-collapse:collapse; background:#fff; border:1px solid var(--line); }
  th, td { text-align:left; padding:10px 12px; border-bottom:1px solid var(--line); vertical-align:top; }
  th { font-size:12px; text-transform:uppercase; letter-spacing:.06em; color:var(--muted); }
  code { font-size:12px; }
  footer { padding:24px 7vw; color:var(--muted); font-size:13px; }
</style>
</head>
<body>
<header>
  <h1>${escapeHtml(pack.title)}</h1>
  <div class="sub">${escapeHtml((session && session.url) || '')} · ${pack.noteCount} findings</div>
</header>
<main>
  <table>
    <thead><tr><th>#</th><th>Action</th><th>Priority</th><th>Visibility</th><th>Note</th><th>Selector</th><th>Viewport</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="7">No notes</td></tr>'}</tbody>
  </table>
</main>
<footer>Generated by Braiwser · read-only client report</footer>
</body>
</html>`;

  return {
    defaultName: `${slug(pack.title)}.html`,
    content: html,
    mime: 'text/html',
  };
}

function escapeHtml(s) {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function slug(s) {
  return String(s || 'report').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60) || 'report';
}

module.exports = { listChecklists, checklistSessionNotes, buildClientPack, buildHtmlReport };
